name: Run Municipio Smoke Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Run Municipio Smoke Tests
        uses: helsingborg-stad/municipio-smoke-tests@v1
        with:
          sitemap-urls: ${{ vars.SITEMAP_URLS }}