name: Run Municipio Smoke Tests sharded
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
        total-shards: [4]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP 
        uses: shivammathur/setup-php@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: 8.3 
          tools: composer:v2

      - name: Install dependencies
        run: composer i

      - name: Run Test
        run: composer run test:local:serve && 
             composer run test:local:run -- --shard=${{ matrix.shard }}/${{ matrix.total-shards }} &&
             composer run test:local:stop